export PATH="/usr/local/bin:$PATH"
export LANG=en_US.UTF-8
alias ga="git add"
alias gaa="git add ."
alias gd="git diff"
alias gcm="git commit -m"
alias gc="git commit"
alias gph="git push"
alias gpl="git pull"
alias gco="git checkout"
alias gcp="git cherry-pick"
alias gs="git status"
alias gst="git stash"
alias gsta="git stash apply"
alias gstd="git stash drop"
alias gb="git branch"
alias glo="git log --oneline"
alias glog="git log --oneline --graph"
alias glg="git log --graph"
alias glp="git log --patch"
alias gfa="git fetch --all"
alias gr="git reset"
alias nr="npm run"
alias obs="open /Applications/Obsidian.app"
alias cobs="cd /Users/taetae/source/repo/obs-repo"
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
